plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

theme: jekyll-theme-slate

title: "CS477"
description: "Artificial Intelligence"

url                      : https://ursinus-cs477-f2023.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "/Modules" # the subpath of your site, e.g. "/blog"
    
# Reading Files
include:
  - .htaccess
  - _pages
  - files

